// scripts/sync.js
// Minimal sync engine: pulls Notion pages, creates PR, updates SystemConnectors

const { Client } = require('@notionhq/client');
const { Octokit } = require('octokit');
const fs = require('fs');
const path = require('path');

const notion = new Client({ auth: process.env.NOTION_API_KEY });
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const REPO_OWNER = 'terra-gaia';
const REPO_NAME = 'terra-gaia-framework';
const BRANCH_BASE = 'main';

async function sync() {
  // 1. Fetch all SystemConnectors for 'notion' from the repo
  const sysConns = await getSystemConnectors();
  const notionConns = sysConns.filter(sc => sc.system === 'notion');

  for (const sc of notionConns) {
    // 2. Fetch Notion page content
    const page = await notion.pages.retrieve({ page_id: sc.external_id });
    // Transform page into canonical Node update (simplified)
    const nodeUpdate = {
      id: sc.node_id,
      title: page.properties.title?.title?.[0]?.plain_text || 'Untitled',
      // ... map other fields
    };

    // 3. Update the corresponding Node JSON file
    const nodePath = `canon/nodes/${sc.node_id}.json`;
    let nodeData = JSON.parse(fs.readFileSync(nodePath, 'utf8'));
    nodeData = { ...nodeData, ...nodeUpdate, updated_at: new Date().toISOString() };
    fs.writeFileSync(nodePath, JSON.stringify(nodeData, null, 2));

    // 4. Create a Pull Request with the changes
    const branchName = `sync/${sc.node_id}-${Date.now()}`;
    await octokit.rest.git.createRef({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      ref: `refs/heads/${branchName}`,
      sha: (await octokit.rest.git.getRef({ owner: REPO_OWNER, repo: REPO_NAME, ref: `heads/${BRANCH_BASE}` })).data.object.sha
    });

    // Commit the change
    await octokit.rest.repos.createOrUpdateFileContents({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      path: nodePath,
      message: `Sync: Update ${sc.node_id} from Notion`,
      content: Buffer.from(JSON.stringify(nodeData)).toString('base64'),
      branch: branchName,
      sha: (await octokit.rest.repos.getContent({ owner: REPO_OWNER, repo: REPO_NAME, path: nodePath })).data.sha
    });

    // Create PR
    const pr = await octokit.rest.pulls.create({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      title: `Sync: ${sc.node_id}`,
      head: branchName,
      base: BRANCH_BASE,
      body: 'Auto-generated by sync engine. Please review and merge if ratification status is correct.'
    });

    console.log(`PR created: ${pr.data.html_url}`);

    // 5. After PR is merged (this is a separate step; we could monitor and update sync_status)
    // For now, we'll leave that to manual merge or a webhook listener.
  }
}

async function getSystemConnectors() {
  const content = await octokit.rest.repos.getContent({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path: 'canon/system_connectors.json'
  });
  return JSON.parse(Buffer.from(content.data.content, 'base64').toString());
}

sync().catch(console.error);
